spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eucl_db?createDatabaseIfNotExist=true
    username: root
    password: Password123!
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com.eucl.prepaidtokensystem: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
jwt:
  secret: jfWAXQzHo/8yDt5JnP9SwZkFmSgOsuUKS/WCK2LWU3c=
  expiration-ms: 900000 # 1 hour